<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PRATIKSHA-07" failures="1" tests="4" name="listeners_testNg.MyClass" time="0.013" errors="0" timestamp="2024-01-03T23:22:26 IST" skipped="0">
  <testcase classname="listeners_testNg.MyClass" name="tc_1" time="0.007">
    <system-out>
      <![CDATA[Tctc_1 execucation is started
tc 1 is running
Tctc_1 is running SuccessFully]]>
    </system-out>
  </testcase> <!-- tc_1 -->
  <testcase classname="listeners_testNg.MyClass" name="tc_2" time="0.001">
    <system-out>
      <![CDATA[Tctc_2 execucation is started
tc 2 is running
Tctc_2 is running SuccessFully]]>
    </system-out>
  </testcase> <!-- tc_2 -->
  <testcase classname="listeners_testNg.MyClass" name="tc_4" time="0.002">
    <system-out>
      <![CDATA[Tctc_4 execucation is started
tc 4 is running
Tctc_4 is running SuccessFully]]>
    </system-out>
  </testcase> <!-- tc_4 -->
  <testcase classname="listeners_testNg.MyClass" name="tc_3" time="0.003">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at listeners_testNg.MyClass.tc_3(MyClass.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
    <system-out>
      <![CDATA[Tctc_3 execucation is started
Tctc_3 is failed,plz check again ]]>
    </system-out>
  </testcase> <!-- tc_3 -->
  <system-out>
    <![CDATA[Tctc_1 execucation is started
tc 1 is running
Tctc_1 is running SuccessFully
Tctc_2 execucation is started
tc 2 is running
Tctc_2 is running SuccessFully
Tctc_4 execucation is started
tc 4 is running
Tctc_4 is running SuccessFully
Tctc_3 execucation is started
Tctc_3 is failed,plz check again ]]>
  </system-out>
</testsuite> <!-- listeners_testNg.MyClass -->
